### ISSUE TITLE
Can't access Admin section

### ISSUE THREAD

**Issue by justinmartin** [churchio/onebody#476]
After upgrading to 3.4.0 I am no longer able to access the admin section.  The following is from the apache error.log file.

```
App 27323 stderr: Started GET "/admin" for 71.86.49.20 at 2015-04-17 11:54:59 -0400
App 27323 stderr: Processing by Administration::DashboardsController#show as HTML
App 27323 stderr:   Rendered administration/dashboards/show.html.haml within layouts/default (89.9ms)
App 27323 stderr: Completed 500 Internal Server Error in 254ms (ActiveRecord: 4.8ms)
App 27323 stderr:
App 27323 stderr: ActionView::Template::Error (Permission denied @ dir_s_mkdir - /var/www/onebody/tmp/cache/5F3):
App 27323 stderr:     3: - content_for :sub_title do
App 27323 stderr:     4:   = t('admin.dashboard.sub_title', version: OneBody.current_version)
App 27323 stderr:     5:
App 27323 stderr:     6: - unless OneBody.up_to_date?
App 27323 stderr:     7:   .alert.alert-warning
App 27323 stderr:     8:     = icon 'fa fa-warning'
App 27323 stderr:     9:     %p= t('admin.dashboard.version_alert.intro_html',
App 27323 stderr:   lib/version_info.rb:22:in `latest_version'
App 27323 stderr:   lib/version_info.rb:31:in `up_to_date?'
App 27323 stderr:   app/views/administration/dashboards/show.html.haml:6:in `_app_views_administration_dashboards_show_html_haml___1945249002768836092_85659000'
App 27323 stderr:
App 27323 stderr:
```

I haven't made any changes other than the upgrade.

**Comment by cessien** [comment]
Did you do a manual install? There was some chatter about this last night

**Comment by hunternet93** [comment]
Check the permissions on OneBody's tmp/cache directory, make sure the web server has write access to the directory and its contents. 

    $ chgrp -R www-data tmp/cache
    $ chmod -R g+rw tmp/cache

**Comment by cessien** [comment]
seems to possibly be a permissions issue. 

try `chgrp www-data /var/www/onebody/tmp -R`
then 'chmod g+w /var/www/onebody/tmp -R'

**Comment by seven1m** [comment]
I think this was resolved in chat by setting 777 permissions on the `tmp/cache` folder.

I've updated the upgrade instructions on the wiki to note this.

**Comment by justinmartin** [comment]
That worked for me.  Thanks for you continual work on this project.  We are getting closer to implementing.

**Comment by warain** [comment]
Hey awesome folks, thanks for providing this code open, I have follow all the directions and have successful installed the program, for my church based non-profit but it seems I am still not able to access the admin, after I changed all the permission as above.

I am running this program on a sub domain, and I am able to access everything else, except the admin
Thanks
![screen shot 2016-05-04 at 1 32 52 am](https://cloud.githubusercontent.com/assets/14221584/15005918/a55c5a6c-1198-11e6-92b4-ed716c007574.png)

**Comment by seven1m** [comment]
@warain please run this on your server in the OneBody directory:

```
sudo chgrp -R www-data tmp/cache
sudo chmod -R g+rw tmp/cache
```

**Comment by seven1m** [comment]
I'm going to reopen this issue since it seems that it is still happening.

**Comment by warain** [comment]
@seven1m thank you for your reply, I have tried the above approach, several times, but the same error shows

**Comment by seven1m** [comment]
This doesn't seem to be an issue with the new debian package. If anyone needs help fixing this on an existing install, please jump in chat at http://chat.church.io/
