### ISSUE TITLE
Timeline AJAX URL's not respecting SSL

### ISSUE THREAD

**Issue by TechWilk** [churchio/onebody#626]
Data URL for AJAX timeline pagination is generated incorrectly:

`<ul class="timeline" data-next-url="http://onebody/stream.json?timeline_page=2">`

**Comment by seven1m** [comment]
@TechWilk I believe this was fixed with the recent update to the example vhost here: https://github.com/churchio/onebody/blob/master/build/deb/vhost/nginx.conf

Please make sure your vhost has the new `proxy_set_header` lines, restart the server, and try again.

**Comment by TechWilk** [comment]
@seven1m The vhost did indeed fix the http://onebody however the ajax URL is still not using https.

```
<ul class="timeline" data-next-url="http://member.allsaints.church/stream.json?timeline_page=2">
    ...
</ul>
<div class="timeline-load-more">
    <a class="btn btn-primary btn-xs" href="?timeline_page=2">load more...</a>
</div>
```

I've run the [SSL setup](https://github.com/churchio/onebody/wiki/SSL-Setup)
```
onebody run rails console
Setting.set_global('Features', 'SSL', true)
Site.current.save
exit
```

And I've also tried the following two vhosts:

vhost #1 (inspired by [Wiki](https://github.com/churchio/onebody/wiki/Serving-with-Nginx)):
```
upstream onebody {
    server 127.0.0.1:3000;
    # if you need additional nodes to scale to more users, you can run:
    #
    #   onebody scale web=5
    #
    # Then put additional lines here for ports 3001 and up:
    #
    # server 127.0.0.1:3001;
    # server 127.0.0.1:3002;
    # server 127.0.0.1:3003;
    # server 127.0.0.1:3004;
}

server {
    listen 443 ssl default_server;

    server_name _;

    ssl_certificate /etc/letsencrypt/live/member.allsaints.church/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/member.allsaints.church/privkey.pem;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;


    client_max_body_size 25m;

    # Tell Nginx where your app's 'public' directory is
    root /opt/onebody/public;

    location @onebody {
        internal;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header  Host             $http_host;
        proxy_redirect    off;
        proxy_pass        http://onebody;
    }

    location / {
        # We are telling nginx here to access the file directly.
        # If it cannot be found, send it on to the thin webserver
        try_files $uri/index.html $uri @onebody;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2)$ {
        expires max;
        log_not_found off;
    }
}


server {
    listen 80;
    server_name member.allsaints.church;
    return 301 https://$host$request_uri;
}
```

vhost #2 (inspired by [default config](https://github.com/churchio/onebody/blob/master/build/deb/vhost/nginx.conf)):
```
upstream onebody {
    server 127.0.0.1:3000;
    # if you need additional nodes to scale to more users, you can run:
    #
    #   onebody scale web=5
    #
    # Then put additional lines here for ports 3001 and up:
    #
    # server 127.0.0.1:3001;
    # server 127.0.0.1:3002;
    # server 127.0.0.1:3003;
    # server 127.0.0.1:3004;
}

server {
    listen 443 ssl default_server;
    client_max_body_size 25m;

    server_name _;

    ssl_certificate /etc/letsencrypt/live/member.allsaints.church/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/member.allsaints.church/privkey.pem;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    location / {
        proxy_pass http://onebody;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}

server {
    listen 80;
    server_name member.allsaints.church;
    return 301 https://$host$request_uri;
}
```

**Comment by seven1m** [comment]
OK I reopend the issue so we can get that fixed. Thanks!

**Comment by seven1m** [comment]
OK, this is fixed on master now. Thanks for letting us know!
